name: axl_mobile_test
description: Testing frameworks and utilities for Flutter apps at AxleHire
version: 0.0.1
publish_to: http://nexus.axlehire.com:7777
axlehire_project_type: package

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  axlehire_lints:
    hosted:
      name: axlehire_lints
      url: http://nexus.axlehire.com:7777
    version: ^0.0.4

flutter:
